#
FROM python:3.10

#
WORKDIR /app

#
COPY ./requirements.txt /app/requirements.txt

#
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

#
COPY ./consumer.py /app/consumer.py
COPY ./infrastructure/event_managers /app/infrastructure/event_managers
COPY ./infrastructure/logging.py /app/infrastructure/logging.py

#
CMD ["python", "consumer.py"]
